### PR TITLE
update docs for px-demo

### PR DESCRIPTION
**Pull request by randyaskin**
I know we were hoping to have Victor and German help with this, but I had a few minutes to spend on it yesterday. Creating a PR so @davidrleonard can gut-check and then @mdwragg can do the npm release voodoo.

### CODE REVIEW

**Comment by randyaskin** [comment]
@davidrleonard Should also mention, I left out the `omit inputType` / `_hideFromConfig` (?) confusion based on our conversation the other day - feel free to include the "right" way to do it.

**Comment by mdwragg** [comment]
💯 Merci 👍

**Comment by davidrleonard** [comment]
@randyaskin I think the only thing wrong is the default `value` for each of the demo properties should actually be `defaultValue`.

**Comment by randyaskin** [comment]
👍 Good catch. Pushed 2.0.2.

**Pull request merged**
